const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const root=path.resolve(__dirname,'../build/variants/admin/assets/web'),out=process.env.HEC_TEST_OUTPUT||path.resolve(__dirname,'../build/review25');fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+req.url.split('?')[0]);if(!file.startsWith(root+path.sep))throw Error();const mime={'.js':'application/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png','.mp4':'video/mp4','.webm':'video/webm','.json':'application/json'}[path.extname(file)]||'text/html';res.setHeader('Content-Type',mime);res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const browser=await chromium.launch({executablePath:process.env.HEC_CHROME_BIN,headless:true,args:['--no-sandbox']});let p;const errors=[],bad=[];
 try{p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'HECAndroid/2.5.0 Test'});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push(r.url())});
 await p.addInitScript(()=>{window.nativeTransfers=[];window.HECRemote={request(id,op,json){setTimeout(()=>HECERP.receive(id,op==='auth.logout'?{value:{ok:true}}:{error:{status:503,message:'خادم غير موصول في الاختبار المحلي'}}),0)}};window.HECDevice={transfer(id,mode,json){const d=JSON.parse(json);nativeTransfers.push({mode,files:d.files.map(f=>({name:f.name,type:f.type,head:atob(f.data).slice(0,8),bytes:atob(f.data).length})),text:d.text});setTimeout(()=>HECNative.receive(id,true,mode==='save'?'حُفظ التصميم في المكان المختار':'عدت من نافذة المشاركة'),50)}};});
 await p.goto('http://127.0.0.1:'+server.address().port+'/index.html#admin');await p.locator('[data-admin-preview]').click();await p.locator('#management-login-form [name=username]').fill('admin');await p.locator('#management-login-form [name=password]').fill('123456');await p.locator('#management-login-form .primary').click();await p.locator('.management-sections').waitFor();
 await p.evaluate(()=>location.hash='detail/TR006');await p.locator('[data-item-media-open=TR006]').click();await p.locator('[data-item-media-files]').first().setInputFiles([path.join(root,'assets/tray.jpg'),path.join(root,'assets/golden-plates.jpg')]);await p.waitForFunction(()=>document.querySelectorAll('[data-item-media-queue] [data-state=success]').length===2);await p.locator('[data-item-media=refresh]').click();assert.equal(await p.locator('.item-media-gallery article').count(),2);await p.locator('[data-item-media-main]').first().click();await p.waitForFunction(()=>document.querySelector('.item-media-gallery b')?.textContent==='الصورة الرئيسية');await p.locator('[data-item-media=close]').click();
 await p.locator('[data-item-design=TR006]').click();await p.locator('#studio-canvas').waitFor();assert((await p.locator('[data-studio-photo]').count())>=3);await p.locator('[data-studio=export-png]').click();await p.waitForFunction(()=>nativeTransfers.length===1&&!HECNative.active());assert.equal((await p.evaluate(()=>nativeTransfers[0])).files[0].type,'image/png');assert((await p.evaluate(()=>nativeTransfers[0])).files[0].head.includes('PNG'));
 await p.locator('[data-studio=save]').click();await p.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('حُفظ التصميم'));
 await p.locator('[data-studio=share]').click();await p.waitForFunction(()=>nativeTransfers.length===2&&!HECNative.active());const share=await p.evaluate(()=>nativeTransfers[1]);assert.equal(share.mode,'share');assert(share.text.includes('TR006'));assert(!share.text.includes('appassets.androidplatform.net'));
 const selected=await p.locator('[data-studio-photo]').count();for(let i=0;i<Math.min(2,selected);i++)await p.locator('[data-studio-photo]').nth(i).check();await p.locator('[data-studio=batch]').click();await p.locator('[data-studio=batch-share]').waitFor();await p.locator('[data-studio=batch-share]').click();await p.waitForFunction(()=>nativeTransfers.length===3&&!HECNative.active());assert((await p.evaluate(()=>nativeTransfers[2])).files.length>=2);
 await p.locator('[data-studio=close]').click();await p.evaluate(()=>location.hash='admin/home-banners');await p.locator('[data-action=management-edit]').first().click();await p.locator('[data-studio-media]').first().click();await p.waitForFunction(()=>document.querySelector('#studio-canvas')?.width===1500);
 await p.locator('[data-studio-product=TR006]').click();const before=await p.evaluate(()=>HECAdminPreview.snapshot()['home-banners'][0]);await p.locator('[data-studio=apply]').click();await p.locator('#hec-studio').waitFor({state:'detached'});await p.locator('#management-record-form [type=submit]').click();await p.locator('#management-record-form').waitFor({state:'hidden'});const after=await p.evaluate(()=>HECAdminPreview.snapshot()['home-banners'][0]);assert.notEqual(before.image,after.image);assert.equal(before.destination,after.destination);assert.deepEqual(before.motion,after.motion);
 await p.evaluate(()=>location.hash='admin/smart-studio');await p.locator('[data-studio=library]').click();await p.locator('[data-studio-doc="0"]').click();await p.locator('#studio-canvas').waitFor();for(const width of [320,390,760]){await p.setViewportSize({width,height:844});await p.waitForTimeout(120);assert(await p.evaluate(()=>document.querySelector('#hec-studio').scrollWidth<=innerWidth+2));await p.screenshot({path:path.join(out,'studio-'+width+'.png')});}await p.locator('[data-studio=close]').click();await p.reload();await p.locator('#management-login-form [name=username]').fill('admin');await p.locator('#management-login-form [name=password]').fill('123456');await p.locator('#management-login-form .primary').click();await p.locator('[data-studio=library]').waitFor();await p.evaluate(()=>location.hash='detail/TR006');await p.locator('[data-item-media-open=TR006]').click();assert.equal(await p.locator('.item-media-gallery article').count(),2);await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>[...document.querySelectorAll('.item-media-gallery img')].every(im=>im.complete&&im.naturalWidth>0));await p.screenshot({path:path.join(out,'photos.png')});
 assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);console.log('PASS Android assets: local login, two photos, primary selection, native PNG save request, native image/text share, multi-image share request, saved design reload, exact banner target preserving navigation and motion, persisted photos, 320/390/760px layout. Native chooser execution still requires an Android device.');
 }catch(e){if(p)await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});if(p)console.error('UI STATUS',await p.locator('[data-studio-status]').allTextContents(),await p.locator('#toast').allTextContents());console.error('ERRORS',errors,'FAILED RESOURCES',bad);throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
