const {harness}=require('./flows.cjs'),assert=require('node:assert/strict');let count=0;function test(n,f){f();count++;console.log('PASS '+n)}
const a=harness(),C=a.c.HECCartCodec,A=a.c.HECOfferEngine;
test('Shared cart round trip keeps Arabic, variants and exact quantities',()=>{const v={v:1,lines:[['FLASK','large',2,'قارورة','أبيض كبير',12500],['K0650','',3,'سكين','حبة',650]]};assert.deepEqual(JSON.parse(JSON.stringify(C.decode(C.encode(v)))),v);assert.equal(C.tokenFrom('رسالة '+a.c.HEC.shareOrigin+'/#cart='+C.encode(v),a.c.HEC.shareOrigin),C.encode(v))});
test('Malformed, oversized, duplicate and authority-bearing payloads are rejected or stripped',()=>{for(const bad of ['%','<script>','A'.repeat(65537)])assert.throws(()=>C.decode(bad));for(const qty of [0,-1,1.5,1000,Infinity])assert.throws(()=>C.encode({v:1,lines:[['A79234','',qty,'صنف','حبة',10]]}));assert.throws(()=>C.encode({v:1,lines:[['A79234','',1,'x','',1],['A79234','',1,'x','',1]]}));const v=C.validate({v:1,user:'admin',role:'System Manager',lines:[['A79234','',1,'x','',1]]});assert.equal('role'in v,false);assert.throws(()=>C.tokenFrom('https://evil.test/#cart='+C.encode(v),a.c.HEC.shareOrigin))});
test('Sharing exports the entire cart with options and no customer identity',()=>{a.click({action:'add',id:'A79234'});a.navigate('detail/FLASK');a.change({dataset:{variant:'FLASK',context:'detail'},value:'large'});a.click({action:'add',id:'FLASK'});a.navigate('cart');const token=a.html().match(/data-cart-share="([^"]+)"/)[1],v=C.decode(token);assert.equal(v.lines.length,2);assert.equal(v.lines[1][1],'large');assert.doesNotMatch(JSON.stringify(v),/customer|phone|address|password/)});
test('Recipient previews, reprices and merges once without losing existing cart',()=>{const b=harness();b.click({action:'add',id:'K0650'});const token=C.encode({v:1,lines:[['A79234','',2,'غير موثوق','حبة',1],['MISSING','',1,'مفقود','حبة',10]]});b.navigate('shared/'+token);assert.equal(b.saved().cart.A79234,undefined);assert.match(b.html(),/السعر الحالي/);assert.match(b.html(),/غير متاح/);b.click({action:'cart-import'});b.click({action:'cart-import'});assert.equal(b.saved().cart.A79234,2);assert.equal(b.saved().cart.K0650,1);assert.equal(b.saved().cart.MISSING,undefined)});
test('Failed shared-cart writes roll back every line',()=>{const b=harness();b.click({action:'add',id:'K0650'});const before=b.mem['hec.phase1.v1'];b.navigate('shared/'+C.encode({v:1,lines:[['A79234','',2,'x','',6000]]}));b.c.localStorage.setItem=()=>{throw Error('full')};b.click({action:'cart-import'});assert.equal(b.mem['hec.phase1.v1'],before)});
test('Merged quantity over the limit never partially imports',()=>{const b=harness(JSON.stringify({cart:{A79234:999}}));b.navigate('shared/'+C.encode({v:1,lines:[['K0650','',1,'x','',650],['A79234','',1,'x','',6000]]}));b.click({action:'cart-import'});assert.equal(b.saved().cart.A79234,999);assert.equal(b.saved().cart.K0650,undefined)});
test('Explicit favorite deletion and clear confirmation leave cart intact',()=>{const b=harness();b.click({action:'add',id:'A79234'});for(const id of ['A79234','K0650'])b.click({action:'favorite',id});b.navigate('favorites');assert.match(b.html(),/favorite-delete/);b.click({action:'favorite-delete',id:'A79234'});assert.deepEqual(b.saved().favorites,['K0650']);b.click({action:'favorites-clear'});assert.equal(b.saved().favorites.length,1);b.click({action:'favorites-confirm-clear'});assert.equal(b.saved().favorites.length,0);assert.equal(b.saved().cart.A79234,1)});
test('Every shop group has its own new-arrivals route and manual scope',()=>{const b=harness();for(const g of b.c.HEC.shopGroups){b.click({department:g.name});b.navigate('shop');assert.match(b.html(),new RegExp('new-arrivals/'+g.id));b.navigate('new-arrivals/'+g.id);assert.match(b.html(),/تسوق \/ /)}const g=b.c.HEC.shopGroups[0];b.c.Commerce.applyConfig({groupNew:[{groupId:g.id,mode:'manual',productIds:['N681012'],excludedIds:[],title:'جديد مختار',limit:5}]});b.navigate('new-arrivals/'+g.id);assert.match(b.html(),/N681012/);assert.doesNotMatch(b.html(),/data-product="A79234"/)});
test('Amount per unit, percentage and automatic remainder sum exactly',()=>{const r=A.allocate(100,[{id:'a',qty:2,base:40,kind:'amount',value:10},{id:'b',qty:1,base:50,kind:'percent',value:30},{id:'c',qty:3,base:10,kind:'auto'}]);assert.equal(r.rows[0].amount,20);assert.equal(r.rows[1].amount,30);assert.equal(r.rows[2].amount,50);assert.equal(r.allocated,100)});
test('Rounding conserves each cent across equal and weighted distributions',()=>{for(const total of [.01,.02,1,10.01,999.99])for(const n of [2,3,7]){const r=A.allocate(total,Array.from({length:n},(_,i)=>({id:'p'+i,qty:i+1,base:i%2?0:3,kind:'auto'})));assert.equal(Math.round(r.rows.reduce((s,r)=>s+r.amount,0)*100),Math.round(total*100))}});
test('Invalid or incomplete allocation cannot be accepted',()=>{for(const rows of [[{id:'a',qty:1,base:10,kind:'amount',value:101}],[{id:'a',qty:1,base:10,kind:'amount',value:90}],[{id:'a',qty:1,base:10,kind:'percent',value:101}],[{id:'a',qty:0,base:10,kind:'auto'}],[{id:'a',qty:1,base:10,kind:'auto'},{id:'a',qty:1,base:10,kind:'auto'}]])assert.throws(()=>A.allocate(100,rows))});
test('ERP Product Bundle requires parent and component prices; schemes require server evaluation',()=>{const b=A.fromERP({doctype:'Product Bundle',name:'PACK',new_item_code:'PACK',items:[{item_code:'a',qty:2},{item_code:'b',qty:1}]},{PACK:90,a:40,b:20});assert.equal(b.total,90);assert.equal(b.rows[0].amount,72);assert.throws(()=>A.fromERP({doctype:'Product Bundle',name:'PACK',new_item_code:'PACK',items:[{item_code:'a',qty:1}]},{}));assert.equal(A.fromERP({doctype:'Promotional Scheme',name:'PROMO'}).requiresServerEvaluation,true)});
test('A complete offer enters the cart as one bundle and exposes its components',()=>{const b=harness();b.navigate('bundle/golden');b.click({action:'bundle-add',id:'golden'});b.navigate('cart');assert.equal(b.saved().cart.BUNDLE_golden,1);assert.match(b.html(),/تفاصيل صنف العرض/);assert.match(b.html(),/N681012|681012/)});
console.log(`${count} commerce and allocation checks passed`);
