const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
const root=path.resolve(__dirname,'../build/variants/customer/assets/web'),out=process.env.HEC_TEST_OUTPUT||path.resolve(__dirname,'../build/customer25-review');fs.mkdirSync(out,{recursive:true});
const origin='https://appassets.androidplatform.net',browser=await chromium.launch({executablePath:process.env.HEC_CHROME_BIN,headless:true,args:['--no-sandbox']}),errors=[],failed=[],checks=[];
const ok=s=>{checks.push(s);console.log('PASS '+s)},go=async(p,h)=>{await p.evaluate(h=>location.hash=h,h);await p.waitForFunction(h=>document.querySelector('#app')?.dataset.route===h.split('/')[0],h)};
let p;
async function page(connected=false){const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 HECAndroid/2.5.0'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url())});
 await page.route(origin+'/**',async route=>{const url=new URL(route.request().url()),rel=url.pathname==='/'?'index.html':url.pathname.slice(1),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){await route.fulfill({status:404,body:'not found'});return;}let body=fs.readFileSync(file);if(connected&&rel==='build-mode.js')body=Buffer.from(body.toString().replace('https://hec-service.invalid','https://fixture.example.test'));const type={'.js':'application/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webm':'video/webm','.mp4':'video/mp4','.html':'text/html'}[path.extname(file)];const range=route.request().headers().range;if(range&&/video\//.test(type)){const m=/bytes=(\d+)-(\d*)/.exec(range);if(m){const start=+m[1],end=m[2]?Math.min(+m[2],body.length-1):body.length-1;await route.fulfill({status:206,contentType:type,headers:{'content-range':`bytes ${start}-${end}/${body.length}`,'accept-ranges':'bytes'},body:body.subarray(start,end+1)});return;}}await route.fulfill({contentType:type,body});});
 await page.addInitScript(()=>{window.nativeCommands=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(a?.href?.startsWith('https://appassets.androidplatform.net/native-')){e.preventDefault();nativeCommands.push(a.href);if(a.pathname==='/native-scan')setTimeout(()=>HECScanner.receive('TR006'),0)}},true)});
 if(connected){let liked=false,comments=[],n=0;const films=JSON.parse(fs.readFileSync(path.join(root,'reels/collection.json')));const chan={store_id:'b'.repeat(32),revision:1,integration_epoch:1,maintenance:false,publication:''};const social=()=>({likes:liked?1:0,liked,commentCount:comments.length,comments,commentsEnabled:true,canInteract:true});await page.exposeFunction('__testRpc',async(op,a)=>{if(op==='public.config')return {modules:{},catalog:[],liveCatalog:false,channel:chan};if(op==='public.version')return chan;if(op==='reels.feed')return {epoch:1,settings:{enabled:true,dataSaver:true},rows:films.map(r=>({...r,url:origin+r.url,kind:'video'}))};if(op==='auth.login'||op==='auth.context')return {authenticated:true,user:'customer@example.test',customer:'CUST-1',roles:[],name:'عميل الاختبار'};if(op==='customer.inbox')return {rows:[]};if(op==='auth.logout')return {ok:true};if(op==='reels.social')return social();if(op==='reels.react'){liked=a.liked;return social()}if(op==='reels.comment'){comments.push({id:String(++n),name:'عميل الاختبار',text:a.text,createdAt:new Date().toISOString(),canDelete:true});return social()}if(op==='reels.comment.delete'){comments=comments.filter(c=>c.id!==a.comment_id);return social()}throw Error('Unsupported fixture operation '+op)});await page.addInitScript(()=>{window.HECRemote={request(id,op,args){__testRpc(op,JSON.parse(args)).then(value=>HECERP.receive(id,{value})).catch(e=>HECERP.receive(id,{error:{status:503,message:e.message}}))}}});}
 await page.goto(origin+'/index.html#home');await page.locator('.bottom-nav').waitFor();return page;}
try{
p=await page();assert.equal(await p.evaluate(()=>typeof HECAdminPreview),'undefined');assert.equal(await p.evaluate(()=>typeof HECStudio),'undefined');await p.evaluate(()=>location.hash='admin');await p.waitForFunction(()=>location.hash==='#home');ok('Customer boots with current assets and no admin dashboard or local admin account');
await p.waitForFunction(()=>HECReels.rows().length===6);await p.locator('[data-reel=expand]').click();await p.locator('.reels-size-button').click();await p.locator('[data-size-preset=small]').click();await p.locator('.reels-size-form [type=submit]').click();const sizes=await p.evaluate(()=>localStorage.getItem('hec.reels.size.v1'));assert(sizes.includes('shortcutWidth'));await p.reload();await p.locator('[data-reel=expand]').waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('hec.reels.size.v1')),sizes);ok('Six packaged reels, glass shortcut, responsive sizing and saved preferences survive restart');
await go(p,'shop');const group=p.locator('.category-sidebar [data-department]').filter({has:p.locator('.reel-group-play')}).first();await group.locator('img').click();assert.equal(await p.locator('#reels-viewer').count(),0);await group.locator('.reel-group-play').click();await p.locator('#reels-viewer').waitFor();ok('Group image opens shopping; only its play badge opens reels');
assert.equal(await p.locator('#reels-viewer video[src]').count(),0);await p.locator('.reel-page').first().locator('.reel-play').click();await p.waitForFunction(()=>{const v=document.querySelector('.reel-page video');return v&&!v.paused&&v.currentTime>.1});assert.match(await p.locator('.reel-page video').first().getAttribute('src'),/^\/reels\/.+\.mp4$/);await p.screenshot({path:out+'/reels-playing.png'});ok('An actual packaged video plays on the Android asset origin without service access');
await p.locator('.reel-page').first().locator('[data-reel-social=cart]').click();if(await p.locator('[data-add-item]').count())await p.locator('[data-add-item]').first().click();assert(await p.evaluate(()=>HECERP.ui().cartLines().length>0));await p.locator('.reel-page').first().locator('[data-reel-social=share]').click();assert.match(await p.evaluate(()=>nativeCommands.at(-1)),/native-reel-share#[A-Za-z0-9_-]+$/);await p.locator('[data-reel=close]').click();await go(p,'cart');assert(await p.locator('.cart-row').count());ok('Reels cart adds to the actual local basket; share invokes the native reel action');
await go(p,'detail/TR006');await p.locator('[data-action=rating-open]').click();await p.locator('[name=score][value="5"]').check();await p.locator('#product-review-form [type=submit]').click();assert.match(await p.locator('.rating-open').textContent(),/★★★★★/);await p.locator('.product-share').click();assert.match(await p.evaluate(()=>nativeCommands.at(-1)),/native-product-share#/);await p.locator('.favorite').click();await go(p,'favorites');await p.locator('[data-action=favorite-delete][data-id=TR006]').click();assert.equal(await p.locator('.product[data-product=TR006]').count(),0);ok('Product rating saves locally; product sharing and explicit favourite removal work');
await go(p,'home');await p.locator('[data-action=barcode]').click();await p.locator('[data-scan-customer]').click();await p.waitForFunction(()=>location.hash==='#search');await p.locator('.product[data-product=TR006]').waitFor();ok('Native barcode callback selects the matching item');
await go(p,'catalog');const cart=p.locator('.floating-cart');await cart.focus();await cart.press('ArrowUp');const cartPos=await p.evaluate(()=>localStorage.getItem('hec.ui.floating-cart.v1'));assert(cartPos);await go(p,'home');await go(p,'catalog');assert.equal(await p.evaluate(()=>localStorage.getItem('hec.ui.floating-cart.v1')),cartPos);ok('Floating basket remains movable with stored position');
await go(p,'cart');const cartShare=await p.locator('a[data-cart-share]').getAttribute('href');assert.match(cartShare,/native-share#/);await p.locator('a[data-cart-share]').click();assert.equal(await p.evaluate(()=>nativeCommands.at(-1)),cartShare);const sharedToken=cartShare.split('#')[1];await go(p,'shared/'+sharedToken);await p.locator('[data-action=cart-import]').click();await p.locator('[data-action=cart-import][disabled]').waitFor();ok('Shared basket has a review/import step and adds its items to the recipient basket');
await go(p,'account');await p.locator('[data-go=courier-login]').click();await p.locator('[data-go=courier-login],.courier-login,#courier-login-form,#courier-live-login').first().waitFor();ok('Courier connection entry remains available');
for(const w of [320,390,760]){await p.setViewportSize({width:w,height:844});for(const route of ['home','shop','offers','favorites','catalog','account','notifications']){await go(p,route);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),route+' overflow '+w);assert(await p.locator('[data-action=top]').count(),route+' missing scroll helper');}await go(p,'home');const taps=await p.locator('.bottom-nav button').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert(taps.every(r=>r.w>=48&&r.h>=48));await p.screenshot({path:out+'/home-'+w+'.png'});}ok('Home, shopping, offers, catalogue, favourites, account and notifications fit 320/390/760px; large navigation and scroll helpers');
await p.close();p=await page(true);await p.waitForFunction(()=>HECERP.live&&HECReels.rows().length===6);await go(p,'erp-account');await p.locator('#erp-customer-login [name=user]').fill('customer@example.test');await p.locator('#erp-customer-login [name=password]').fill('test-password');await p.locator('#erp-customer-login .primary').click();await p.waitForFunction(()=>HECERP.context()?.customer==='CUST-1');await go(p,'home');await p.locator('[data-reel=expand]').click();await p.locator('[data-reel=all]').click();await p.locator('.reel-page').first().locator('[data-reel-social=like]').click();await p.locator('.reel-page').first().locator('[data-reel-social=like][aria-pressed=true]').waitFor();await p.locator('.reel-page').first().locator('[data-reel-social=comment]').click();await p.locator('#reel-comment-text').fill('تعليق الاختبار');await p.locator('.social-comment-form [type=submit]').click();await p.locator('.social-comment').waitFor();await p.locator('[data-comment-delete]').click();await p.waitForFunction(()=>!document.querySelector('.social-comment'));ok('Connected fixture: account login, reel like and matching favourite, comment creation and deletion use service operations');
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({checks,errors,failed,fixtureOnly:true,nativeIntents:'captured in browser; no physical Android device'},null,2));
}catch(e){console.error('ERRORS',errors,'FAILED',failed);if(p&&!p.isClosed()){await p.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.html',await p.content());}throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
