const {harness}=require('./flows.cjs'),assert=require('node:assert/strict');let n=0;
function test(name,fn){fn();n++;console.log('PASS '+name)}
function enter(a){a.navigate('account');a.click({action:'customer-enter'})}
test('All eight shortcut tiles and ordered home sections are rendered',()=>{const a=harness(),s=a.html();assert.equal((s.match(/class="home-shortcuts"/g)||[]).length,1);for(const text of ['campaign-new.jpg','deal-home.jpg','data-countdown="golden"','منظفات','مفروشات','category-rail','product-rail'])assert.ok(s.includes(text),text);assert.ok(s.indexOf('banner-cleaning.jpg')<s.indexOf('home-banner'));assert.match(s,/data-key="youtube"/)});
test('All customer routes render and private previews are gated',()=>{const a=harness();for(const r of ['profile','email','password','wallet','returns','loyalty','affiliate','messages']){a.navigate(r);assert.match(a.html(),['loyalty','affiliate'].includes(r)?/غير مفعّلة/:/customer-enter/)}enter(a);for(const r of ['profile','email','password','wallet','returns','loyalty','affiliate','messages','language','notifications','offers','flash/golden','innovative']){a.navigate(r);assert.ok(a.html().length>200,r)}});
test('Price range plus brand filtering affects real catalog results',()=>{const a=harness();a.navigate('search');a.submit('filter-form',{min:'٥٠٠٠',max:'6000',brand0:'دي إس بي'});assert.match(a.html(),/data-product="A79234"/);assert.match(a.html(),/data-product="KJ3052"/);assert.doesNotMatch(a.html(),/data-product="N12"/);assert.doesNotMatch(a.html(),/data-product="CA015"/)});
test('Invalid price ranges leave previous filters unchanged',()=>{const a=harness();a.navigate('search');a.submit('filter-form',{min:'5000',max:'6000'});const before=a.html();a.submit('filter-form',{min:'9000',max:'1'});assert.equal(a.html(),before);a.submit('filter-form',{min:'Infinity',max:'1'});assert.equal(a.html(),before)});
test('Filter clear restores all catalog results',()=>{const a=harness();a.navigate('search');a.submit('filter-form',{section0:'العناية الشخصية'});assert.doesNotMatch(a.html(),/data-product="CA015"/);a.click({action:'filter-clear'});assert.match(a.html(),/data-product="CA015"/)});
test('Golden-hour search is scoped to campaign products',()=>{const a=harness();a.navigate('flash/golden');a.submit('flash-search-form',{q:'A79234'});assert.doesNotMatch(a.html(),/data-product="A79234"/);assert.match(a.html(),/لا توجد نتائج/);a.submit('flash-search-form',{q:'N009'});assert.match(a.html(),/data-product="N009"/)});
test('Countdown reaches zero and never becomes negative',()=>{const a=harness(),c=a.c.HEC.campaigns[0],epoch=a.saved().campaignEpoch;assert.match(a.c.Experience.countdown(c,epoch+c.duration),/انتهى العرض/);assert.match(a.c.Experience.countdown(c,epoch+c.duration+99999),/انتهى العرض/);assert.doesNotMatch(a.c.Experience.countdown(c,epoch+c.duration-1000),/انتهى العرض/)});
test('Campaign clock persists across restarts without reset',()=>{const a=harness(),epoch=a.saved().campaignEpoch;const b=harness(a.mem['hec.phase1.v1']);b.click({action:'favorite',id:'A79234'});assert.equal(b.saved().campaignEpoch,epoch)});
test('Profile saves escaped bounded fields and normalizes phone',()=>{const a=harness();enter(a);a.navigate('profile');a.submit('customer-profile-form',{name:'<img onerror=evil>',phone:'٧٧٧١٢٣٤٥٦'});assert.equal(a.saved().profile.phone,'777123456');a.navigate('account');assert.match(a.html(),/&lt;img/);assert.doesNotMatch(a.html(),/<img onerror/);a.submit('customer-email-form',{email:'invalid'});assert.equal(a.saved().profile.email,'');a.submit('customer-email-form',{email:'demo@example.test'});assert.equal(a.saved().profile.email,'demo@example.test')});
test('Passwords are reset and never persisted',()=>{const a=harness();enter(a);a.navigate('password');const f=a.submit('customer-password-form',{old:'old-secret',new:'Long-Secure-Demo-123',confirm:'Long-Secure-Demo-123'});assert.ok(f.didReset);assert.doesNotMatch(JSON.stringify(a.mem),/Long-Secure|old-secret/)});
test('Wallet requests are drafts and do not create financial balances',()=>{const a=harness();enter(a);a.navigate('wallet');a.submit('wallet-form',{type:'deposit',amount:'٢٥٠٠',note:'Demo'});assert.equal(a.saved().walletRequests[0].amount,2500);assert.equal(a.saved().walletRequests[0].status,'draft');assert.match(a.html(),/<strong>0 ر.ي<\/strong>/);a.submit('wallet-form',{type:'deposit',amount:'-1'});assert.equal(a.saved().walletRequests.length,1)});
test('Return quantity is limited to order quantity and prevents duplicates',()=>{const a=harness();a.click({action:'add',id:'A79234'});a.submit('checkout-form',{name:'Demo',phone:'777123456',address:'Demo Address'});enter(a);a.navigate('returns');const line=a.saved().orders[0].id+'/0';a.submit('return-form',{line,qty:'2',reason:'damaged'});assert.equal(a.saved().returns.length,0);a.submit('return-form',{line,qty:'1',reason:'damaged',note:'تالف'});assert.equal(a.saved().returns.length,1);a.submit('return-form',{line,qty:'1',reason:'damaged'});assert.equal(a.saved().returns.length,1)});
test('Message create, edit, search and confirmed deletion work',()=>{const a=harness();enter(a);a.navigate('messages');a.submit('customer-message-form',{subject:'استفسار',body:'تفاصيل الاستفسار عن منتج'});const id=a.saved().messages[0].id;a.submit('customer-message-form',{draftId:id,subject:'تعديل',body:'رسالة معدلة محفوظة'});assert.equal(a.saved().messages.length,1);assert.equal(a.saved().messages[0].subject,'تعديل');a.click({action:'delete-local',kind:'messages',id});assert.equal(a.saved().messages.length,1);a.click({action:'confirm-delete-local',kind:'messages',id});assert.equal(a.saved().messages.length,0)});
test('Failed new form write preserves saved state and retry is atomic',()=>{const a=harness();enter(a);a.navigate('messages');const before=a.mem['hec.phase1.v1'],write=a.c.localStorage.setItem;a.c.localStorage.setItem=()=>{throw Error('full')};a.submit('customer-message-form',{subject:'اختبار',body:'هذه رسالة اختبار'});assert.equal(a.mem['hec.phase1.v1'],before);a.c.localStorage.setItem=write;a.submit('customer-message-form',{subject:'اختبار',body:'هذه رسالة اختبار'});assert.equal(a.saved().messages.length,1)});
test('Logout blocks private pages and stale submissions without deleting drafts',()=>{const a=harness();enter(a);a.submit('customer-message-form',{subject:'اختبار',body:'هذه رسالة اختبار'});a.click({action:'customer-confirm-logout'});a.navigate('messages');assert.match(a.html(),/customer-enter/);a.submit('customer-message-form',{subject:'stale',body:'blocked message'});assert.equal(a.saved().messages.length,1)});
test('Notification unread count updates and persists',()=>{const a=harness();assert.equal(a.c.Experience.unread(),1);a.click({action:'notifications-read'});assert.equal(a.c.Experience.unread(),0);const b=harness(a.mem['hec.phase1.v1']);assert.equal(b.c.Experience.unread(),0)});
test('English locale persists and renders English customer menus',()=>{const a=harness();a.submit('language-form',{locale:'en'});a.navigate('account');assert.match(a.html(),/Manage wallet/);assert.equal(a.saved().locale,'en');const b=harness(a.mem['hec.phase1.v1']);b.navigate('language');assert.match(b.html(),/Choose your app language/);b.submit('language-form',{locale:'ar'});b.navigate('account');assert.match(b.html(),/إدارة المحفظة/)});
test('Hostile restored new fields cannot inject credentials or financial authority',()=>{const a=harness();const s=a.c.HECStore.customer({profile:{name:'Test',token:'secret'},walletRequests:[{id:'W-TEST',amount:500,type:'deposit',status:'paid',password:'secret'}],locale:'evil',messages:[{id:'M-TEST',subject:'a',body:'b',api_key:'secret'}]});assert.equal(s.walletRequests[0].status,'draft');assert.equal(s.locale,'ar');assert.doesNotMatch(JSON.stringify(s),/secret|api_key|token|password/)});
test('Loading, empty, failure and retry states are distinct',()=>{const a=harness();for(const [state,needle] of [['loading','skeleton-page'],['empty','لا توجد بيانات'],['error','تعذر تحميل المحتوى']]){a.c.Experience.setMode(state);a.navigate('offers');assert.match(a.html(),new RegExp(needle))}a.click({action:'experience-retry'});assert.match(a.html(),/featured-campaign/)});
test('Order history filter distinguishes drafts from unsent real orders',()=>{const a=harness();a.click({action:'add',id:'A79234'});a.submit('checkout-form',{name:'Demo',phone:'777123456',address:'Demo Address'});a.navigate('orders');a.submit('orders-filter-form',{q:'unknown',status:'all'});assert.match(a.html(),/لا توجد طلبات/);a.click({action:'orders-clear'});assert.match(a.html(),/order-link/);a.click({action:'order-tab',value:'sent'});assert.match(a.html(),/لم تُرسل طلبات فعلية/)});
test('Privacy clear resets all new customer data while preserving courier',()=>{const a=harness();enter(a);a.submit('customer-message-form',{subject:'مسودة',body:'مسودة للاختبار'});a.click({action:'confirm-clear-customer'});assert.equal(a.saved().messages.length,0);assert.equal(a.saved().profile.name,'');assert.equal(a.saved().locale,'ar')});
test('Verified QR link opens a reviewed external destination and rejects hostile URLs',()=>{const a=harness();a.c.URL=URL;assert(a.c.Experience.validExternal(a.c.HEC.externalLinks.facebook,'facebook'));for(const u of ['javascript:alert(1)','https://facebook.com.evil.test/store','https://user:pass@facebook.com/store','http://facebook.com/store','https://facebook.com:8443/store','https://facebook.com/%73tore'])assert(!a.c.Experience.validExternal(u,'facebook'),u);a.click({action:'external',key:'facebook'});assert.match(a.elements['#dialog'].innerHTML,/https:\/\/www.facebook.com\/HaithemEkhwanCenter\//);a.click({action:'external',key:'play'});assert.doesNotMatch(a.elements['#dialog'].innerHTML,/href=/)});
console.log(`${n} new experience checks passed`);
