/* Dependency-free functional checks of the actual app event handlers and rendered output.
   This is not a substitute for Android device/visual testing. */
const {readFileSync}=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const path=require('node:path'),root=path.join(__dirname,'../app/src/main/assets/web');
let tests=0;
function harness(storage='{}',courierStorage='null',demo=true){
 const listeners={},elements={};for(const id of ['#app','#dialog','#toast','#login-error','#courier-login-message','#courier-form-message','#courier-password','#demo-collected','#storage-status'])elements[id]={innerHTML:'',textContent:'',type:'password',checked:false,open:false,dataset:{},addEventListener(){},classList:{add(){},remove(){}},close(){this.open=false},showModal(){this.open=true}};
 const mem={'hec.phase1.v1':storage,'hec.courier.demo.v1':courierStorage},loc={_hash:'#home',get hash(){return this._hash},set hash(v){this._hash=v.startsWith('#')?v:'#'+v}},c={console,Intl,Date,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),FormData:class{constructor(f){this.v=f.values}get(k){return this.v[k]||null}has(k){return k in this.v}entries(){return Object.entries(this.v)}},setTimeout:()=>1,clearTimeout(){},document:{documentElement:{dataset:{}},querySelector:s=>elements[s],querySelectorAll:()=>[],addEventListener:(k,f)=>{const old=listeners[k];listeners[k]=old?(e)=>{old(e);f(e)}:f}},localStorage:{getItem:k=>mem[k],setItem:(k,v)=>mem[k]=v},location:loc,history:{length:1,replaceState(){},back(){}},navigator:{}};
 c.window=c;c.scrollY=0;c.scrollTo=()=>{};c.addEventListener=(k,f)=>listeners[k]=f;
 vm.createContext(c);for(const file of ['data.js','experience-data.js','cart-codec.js','offer-engine.js','enhancements-data.js','storage.js','item-source.js','bundle-order.js','scanner.js','theme.js','marketing.js','media.js','fulfillment.js','notifications.js','courier.js','experience.js','commerce.js','engagement.js','automation.js','management-config.js','management-preview.js','management-api.js','management-picker.js','marketing-editor.js','slides-editor.js','engagement-editor.js','management.js','app.js'])vm.runInContext(readFileSync(path.join(root,file),'utf8'),c);
 if(demo){c.Courier.click({dataset:{action:'courier-enter'}});loc.hash='#home';listeners.hashchange()}
 const navigate=r=>{loc.hash='#'+r;listeners.hashchange()};const click=dataset=>{listeners.click({target:{closest:selector=>{if(selector.includes('data-scan')||selector.includes('data-pick-component')||selector.includes('floating-cart'))return null;return {dataset,setAttribute(){}}}}});if(loc.hash!=='#'+current){current=loc.hash.slice(1);listeners.hashchange()}};let current='home';
 const submit=(id,values)=>{const f={id,values,reportValidity:()=>true,reset(){this.didReset=true},elements:{password:{value:values.password||'secret'}}};listeners.submit({preventDefault(){},target:f});if(current!==loc.hash.slice(1)){current=loc.hash.slice(1);listeners.hashchange()}return f};
 const change=target=>{target.matches=target.matches||(()=>false);target.closest=target.closest||(()=>null);listeners.change({target})};
 return {c,mem,elements,navigate,click,change,submit,html:()=>elements['#app'].innerHTML,saved:()=>JSON.parse(mem['hec.phase1.v1']),courier:()=>JSON.parse(mem['hec.courier.demo.v1'])};
}
function test(name,f){f();tests++;console.log('PASS '+name)}
const a=harness();
test('Home renders source banner and first products',()=>{assert.match(a.html(),/washers.jpg/);assert.match(a.html(),/A79234/);assert.match(a.html(),/KJ3052/)});
test('Quantity increase and add preserve quantity and total',()=>{a.click({action:'plus',id:'A79234',context:'card'});a.click({action:'add',id:'A79234'});assert.equal(a.saved().cart.A79234,2);a.navigate('cart');assert.match(a.html(),/12,000 ر.ي/)});
test('Second product adds into combined total',()=>{a.click({action:'add',id:'K0650'});assert.equal(a.saved().cart.K0650,1);assert.match(a.html(),/12,650 ر.ي/)});
test('Cart minimum is one',()=>{a.click({action:'minus',id:'K0650',context:'cart'});assert.equal(a.saved().cart.K0650,1)});
test('Deletion requires confirmation',()=>{a.click({action:'remove',id:'K0650'});assert.equal(a.saved().cart.K0650,1);assert.equal(a.elements['#dialog'].open,true);a.click({action:'confirm-remove',id:'K0650'});assert.equal(a.saved().cart.K0650,undefined)});
test('Favorites toggle and persist',()=>{a.click({action:'favorite',id:'A79234'});assert.ok(a.saved().favorites.includes('A79234'));a.click({action:'favorite',id:'A79234'});assert.equal(a.saved().favorites.length,0)});
test('Name search returns relevant results',()=>{a.submit('search-form',{q:'حلاقة'});assert.match(a.html(),/A79234/);assert.doesNotMatch(a.html(),/data-product="KJ3052"/)});
test('Product-code search',()=>{a.submit('barcode-form',{code:'KJ3052'});assert.match(a.html(),/data-product="KJ3052"/);assert.doesNotMatch(a.html(),/data-product="A79234"/)});
test('Empty result state',()=>{a.submit('search-form',{q:'nonexistent-000'});assert.match(a.html(),/لا توجد نتائج/)});
test('Search text is escaped',()=>{a.submit('search-form',{q:'<script>alert(1)</script>'});assert.doesNotMatch(a.html(),/<script>alert/)});
test('Filter offers only',()=>{a.submit('search-form',{q:''});a.submit('filter-form',{category:'الكل',offers:'on'});assert.match(a.html(),/data-product="A79234"/);assert.doesNotMatch(a.html(),/data-product="KJ3052"/)});
test('Sort price ascending',()=>{a.submit('filter-form',{category:'الكل'});a.submit('sort-form',{sort:'low'});assert.ok(a.html().indexOf('data-product="J0350"')<a.html().indexOf('data-product="CA015"'))});
test('Checkout saves local draft with exact snapshot and clears cart',()=>{a.navigate('checkout');a.submit('checkout-form',{name:'عميل تجريبي',phone:'777123456',address:'صنعاء — شارع الاختبار',note:'اختبار'});const s=a.saved();assert.equal(s.orders[0].total,12000);assert.equal(s.orders[0].lines[0].qty,2);assert.equal(s.orders[0].status,'draft');assert.deepEqual(s.cart,{});assert.match(a.html(),/لم يتم إرسالها/)});
test('Addresses escaped and persisted',()=>{a.submit('address-form',{name:'<img onerror=alert(1)>',address:'عنوان تجريبي'});a.navigate('addresses');assert.match(a.html(),/&lt;img/);assert.doesNotMatch(a.html(),/<img onerror/)});
test('Persistent state restores on new app session',()=>{const b=harness(a.mem['hec.phase1.v1']);b.navigate('orders');assert.match(b.html(),/مسودة محلية/)});
test('Malformed storage recovers',()=>{assert.match(harness('{bad json').html(),/مقترحات الهيثم/)});
test('Unknown product and order safe empty states',()=>{a.navigate('detail/invalid');assert.match(a.html(),/المنتج غير موجود/);a.navigate('order/invalid');assert.match(a.html(),/الطلب غير موجود/)});
test('All defined screens render',()=>{for(const r of ['home','shop','offers','detail/A79234','cart','favorites','account','orders','checkout','addresses','login','admin','admin-list/9','help','catalog','search','notifications']){a.navigate(r);assert.ok(a.html().length>100,r)}});
test('Corrupt quantities and unknown IDs are normalized',()=>{const b=harness(JSON.stringify({cart:{A79234:-1,KJ3052:100000,unknown:3}}));b.navigate('cart');assert.match(b.html(),/>999<\/output>/);assert.doesNotMatch(b.html(),/unknown/)});


const v=harness();
test('Same product retains independent small and large lines and prices',()=>{v.navigate('detail/FLASK');v.click({action:'add',id:'FLASK'});v.change({dataset:{variant:'FLASK',context:'detail'},value:'large'});v.click({action:'plus',id:'FLASK',context:'detail'});v.click({action:'add',id:'FLASK'});v.navigate('cart');assert.equal(v.saved().cart.FLASK,1);assert.equal(v.saved().cart['FLASK~large'],2);assert.match(v.html(),/12,500 ر.ي/);assert.match(v.html(),/10,000 ر.ي/)});
test('Changing one variant quantity never changes the other line',()=>{v.click({action:'plus',id:'FLASK',line:'FLASK~large',context:'cart'});assert.equal(v.saved().cart.FLASK,1);assert.equal(v.saved().cart['FLASK~large'],3);assert.match(v.html(),/17,500 ر.ي/)});
test('Variant state survives a restart with correct prices',()=>{const b=harness(v.mem['hec.phase1.v1']);b.navigate('cart');assert.match(b.html(),/17,500 ر.ي/);b.navigate('detail/FLASK');assert.match(b.html(),/value="large" selected/)});
test('Opening cart detail restores the selected line variant',()=>{v.click({go:'detail/FLASK',chooseVariant:'small'});assert.match(v.html(),/value="small" selected/)});
test('Variant merge conserves quantity and updates the unit price',()=>{v.navigate('cart');v.change({dataset:{variant:'FLASK',context:'cart',line:'FLASK~large'},value:'small'});assert.equal(v.saved().cart.FLASK,4);assert.equal(v.saved().cart['FLASK~large'],undefined);assert.match(v.html(),/10,000 ر.ي/)});
test('Variant checkout records label and exact price snapshot',()=>{v.navigate('checkout');v.submit('checkout-form',{name:'عميل تجريبي',phone:'777123456',address:'عنوان تجريبي'});assert.equal(v.saved().orders[0].total,10000);assert.equal(v.saved().orders[0].lines[0].price,2500);assert.match(v.html(),/أبيض - صغير/)});
test('Variant merge over 999 is rejected without loss',()=>{const b=harness(JSON.stringify({cart:{FLASK:999,'FLASK~large':2}}));b.navigate('cart');b.change({dataset:{variant:'FLASK',context:'cart',line:'FLASK~large'},value:'small'});b.click({action:'favorite',id:'FLASK'});assert.equal(b.saved().cart.FLASK,999);assert.equal(b.saved().cart['FLASK~large'],2)});
test('Invalid multi-part and nonexistent variant IDs cannot become cart lines',()=>{const b=harness(JSON.stringify({cart:{'FLASK~invalid':1,'FLASK~large~x':2,FLASK:1}}));b.navigate('cart');assert.match(b.html(),/2,500 ر.ي/);assert.doesNotMatch(b.html(),/data-line="FLASK~/)});
test('Filtered catalog does not duplicate featured products',()=>{const b=harness();b.click({subcategory:'العناية الشخصية'});assert.equal((b.html().match(/data-product="A79234"/g)||[]).length,1);assert.doesNotMatch(b.html(),/class="bottom-nav"/)});
test('Department drilldown and empty category render',()=>{const b=harness();b.navigate('shop');b.click({department:'أجهزة وإلكترونيات'});assert.match(b.html(),/cat-fans.jpg/);b.click({subcategory:'مراوح ومكيفات'});assert.match(b.html(),/لا توجد نتائج/)});
test('Global-only filter is cleared by a fresh search',()=>{const b=harness();b.navigate('catalog');b.change({id:'global-filter',checked:true});assert.match(b.html(),/لا توجد نتائج/);b.submit('search-form',{q:'حلاقة'});assert.match(b.html(),/data-product="A79234"/)});
const c=harness();
test('Courier screens render through all defined routes',()=>{for(const r of ['courier-login','courier-home','courier-deliveries','courier-earnings','courier-collected','courier-account','courier-profile','courier-contact','courier-password','courier-forgot','courier-detail/DEMO-7663','tracking/DEMO-2452']){c.navigate(r);assert.ok(c.html().length>200,r)}});
test('Courier availability prevents accepting new offers while offline',()=>{c.navigate('courier-home');c.click({action:'courier-availability'});c.click({action:'courier-accept',id:'DEMO-7663'});assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-7663').status,'offered');c.click({action:'courier-availability'})});
test('Accepting an offer twice only transitions it once',()=>{c.click({action:'courier-accept',id:'DEMO-7663'});c.click({action:'courier-accept',id:'DEMO-7663'});assert.equal(c.courier().jobs.filter(j=>j.id==='DEMO-7663').length,1);assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-7663').status,'accepted')});
test('Rejecting a different offer needs confirmation and never changes accepted ones',()=>{c.click({action:'courier-reject',id:'DEMO-6050'});assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-6050').status,'offered');c.click({action:'courier-confirm-reject',id:'DEMO-6050'});c.click({action:'courier-confirm-reject',id:'DEMO-7663'});assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-6050').status,'rejected');assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-7663').status,'accepted')});
test('Delivery cannot jump directly from accepted to delivered',()=>{c.click({action:'courier-confirm-deliver',id:'DEMO-7663'});assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-7663').status,'accepted')});
test('Confirmed cash delivery updates earnings and collection exactly once',()=>{c.click({action:'courier-onway',id:'DEMO-7663'});c.click({action:'courier-deliver',id:'DEMO-7663'});assert.equal(c.courier().jobs.find(j=>j.id==='DEMO-7663').status,'onway');c.elements['#demo-collected'].checked=true;c.click({action:'courier-confirm-deliver',id:'DEMO-7663'});c.click({action:'courier-confirm-deliver',id:'DEMO-7663'});const js=c.courier().jobs.filter(j=>j.status==='delivered');assert.equal(js.length,3);assert.equal(js.reduce((n,j)=>n+j.collected,0),203612);assert.equal(js.reduce((n,j)=>n+j.earnings,0),295);assert.ok(js.find(j=>j.id==='DEMO-7663').paid)});
test('Courier transitions and totals survive restart',()=>{const b=harness('{}',c.mem['hec.courier.demo.v1']);b.navigate('courier-home');assert.match(b.html(),/203,612 ر.ي/);assert.match(b.html(),/295 ر.ي/)});
test('Prepaid deliveries do not collect cash again',()=>{const b=harness();b.navigate('courier-home');b.click({action:'courier-accept',id:'DEMO-6050'});b.click({action:'courier-onway',id:'DEMO-6050'});b.elements['#demo-collected'].checked=true;b.click({action:'courier-confirm-deliver',id:'DEMO-6050'});assert.equal(b.courier().jobs.find(j=>j.id==='DEMO-6050').collected,0)});
test('Courier password is cleared and never stored during offline sign-in',()=>{c.navigate('courier-login');const f=c.submit('courier-login-form',{identifier:'demo@example.test',password:'Test-Secret-123'});assert.equal(f.elements.password.value,'');assert.doesNotMatch(JSON.stringify(c.mem),/Test-Secret-123/);assert.match(c.elements['#courier-login-message'].textContent,/لم تُرسل/)});
test('Profile input is escaped and password change clears its form',()=>{c.submit('courier-profile-form',{name:'<img onerror=alert(1)>'});c.navigate('courier-account');assert.match(c.html(),/&lt;img/);assert.doesNotMatch(c.html(),/<img onerror/);const f=c.submit('courier-password-form',{old:'secret111',new:'secret222',confirm:'secret333'});assert.ok(f.didReset);assert.match(c.elements['#courier-form-message'].textContent,/غير متطابقتين/);assert.doesNotMatch(JSON.stringify(c.mem),/secret222/)});
test('All four tracking stages have the correct completed connectors',()=>{c.navigate('tracking/DEMO-2452');for(let i=0;i<4;i++){c.change({id:'tracking-stage',value:String(i)});assert.equal((c.html().match(/connector-complete/g)||[]).length,i)}});
test('A zero-delivery account persists and has clear empty states',()=>{c.navigate('courier-account');c.click({action:'courier-empty'});assert.ok(c.courier().jobs.length>0);c.click({action:'courier-confirm-empty'});assert.equal(c.courier().jobs.length,0);const b=harness('{}',c.mem['hec.courier.demo.v1']);b.navigate('courier-home');assert.match(b.html(),/لا توجد طلبات توصيل جديدة/);b.navigate('courier-earnings');assert.match(b.html(),/لا توجد بيانات/)});
test('Corrupted courier amounts cannot alter demo financial fixtures',()=>{const b=harness('{}',JSON.stringify({jobs:[{id:'DEMO-4504',amount:-3,earnings:999999,collected:99999,status:'delivered',paid:true}],profile:{}}));b.navigate('courier-home');assert.match(b.html(),/150 ر.ي/);assert.doesNotMatch(b.html(),/999,999/)});
test('Failed cart write rolls back and retry saves exactly once',()=>{const b=harness();const write=b.c.localStorage.setItem;b.c.localStorage.setItem=()=>{throw Error('QuotaExceededError')};b.click({action:'add',id:'A79234'});assert.equal(b.elements['#storage-status'].hidden,false);assert.doesNotMatch(b.elements['#toast'].innerHTML,/أُضيف/);b.c.localStorage.setItem=write;b.click({action:'add',id:'A79234'});assert.equal(b.saved().cart.A79234,1);assert.equal(b.elements['#storage-status'].hidden,true)});
test('Failed checkout keeps cart and creates no phantom order',()=>{const b=harness();b.click({action:'add',id:'A79234'});const before=b.mem['hec.phase1.v1'],write=b.c.localStorage.setItem;b.c.localStorage.setItem=()=>{throw Error('full')};b.navigate('checkout');const form={name:'عميل اختبار',phone:'٧٧٧١٢٣٤٥٦',address:'عنوان تجريبي'};b.submit('checkout-form',form);assert.equal(b.mem['hec.phase1.v1'],before);b.c.localStorage.setItem=write;b.submit('checkout-form',form);assert.equal(b.saved().orders.length,1);assert.equal(b.saved().orders[0].customer.phone,'777123456');assert.deepEqual(b.saved().cart,{})});
test('Local schema drops invalid orders and unknown private fields',()=>{const b=harness();const s=b.c.HECStore.customer({password:'secret',orders:[null,{}, {id:'<img>',lines:[]},{id:'D-VALID',total:999999,status:'paid',lines:[null,{id:'unknown',price:2},{id:'A79234',price:6000,qty:2}],customer:{name:'Test',token:'secret'}}],addresses:[null,{}, {name:'Home',address:'Address',secret:'token'}]});assert.equal(s.orders.length,1);assert.equal(s.orders[0].total,12000);assert.equal(s.orders[0].status,'draft');assert.equal(s.addresses.length,1);assert.doesNotMatch(JSON.stringify(s),/secret|token|password/)});
test('Canonical variant aliases merge once and malformed keys are discarded',()=>{const b=harness(JSON.stringify({cart:{FLASK:2,'FLASK~small':3,'FLASK~large~evil':4,'A79234~small':5}}));b.click({action:'favorite',id:'A79234'});assert.deepEqual(b.saved().cart,{FLASK:5})});
test('Stale quantity events cannot create or change other product lines',()=>{const b=harness();b.click({action:'add',id:'K0650'});const before=b.mem['hec.phase1.v1'];b.click({action:'plus',id:'A79234',line:'K0650',context:'cart'});b.click({action:'plus',id:'A79234',line:'A79234',context:'cart'});b.change({dataset:{variant:'UNKNOWN',context:'cart'},value:'bad'});assert.equal(b.mem['hec.phase1.v1'],before)});
test('Arabic search accepts spelling variants and Arabic product-code digits',()=>{const b=harness();b.submit('search-form',{q:'حلاقه'});assert.match(b.html(),/data-product="A79234"/);b.submit('search-form',{q:'A٧٩٢٣٤'});assert.match(b.html(),/data-product="A79234"/);assert.doesNotMatch(b.html(),/data-product="KJ3052"/)});
test('Whitespace names and punctuation-only phones cannot save drafts',()=>{const b=harness();b.click({action:'add',id:'A79234'});b.submit('checkout-form',{name:'   ',phone:'777123456',address:'عنوان تجريبي'});b.submit('checkout-form',{name:'عميل اختبار',phone:'-------',address:'عنوان تجريبي'});assert.equal(b.saved().orders.length,0);assert.equal(b.saved().cart.A79234,1)});
test('Draft identifiers remain distinct even at identical clock timestamps',()=>{const b=harness();b.c.Date=class extends Date{static now(){return 123456789}};for(let i=0;i<2;i++){b.click({action:'add',id:'A79234'});b.submit('checkout-form',{name:'Test',phone:'777123456',address:'Address'})}assert.equal(b.saved().orders.length,2);assert.notEqual(b.saved().orders[0].id,b.saved().orders[1].id)});
test('Undo restores only the deleted line and cannot duplicate it',()=>{const b=harness();b.click({action:'add',id:'A79234'});b.click({action:'add',id:'K0650'});b.click({action:'confirm-remove',id:'A79234'});assert.match(b.elements['#toast'].innerHTML,/تراجع/);b.click({action:'undo-remove'});b.click({action:'undo-remove'});assert.deepEqual(b.saved().cart,{K0650:1,A79234:1})});
test('Privacy clear needs confirmation and only clears the selected role',()=>{const b=harness();b.mem.unrelated='keep';b.click({action:'add',id:'A79234'});b.click({action:'courier-availability'});const courier=b.mem['hec.courier.demo.v1'];b.navigate('privacy');b.click({action:'clear-customer'});b.click({action:'close'});assert.equal(b.saved().cart.A79234,1);b.click({action:'confirm-clear-customer'});assert.deepEqual(b.saved().cart,{});assert.equal(b.mem['hec.courier.demo.v1'],courier);assert.equal(b.mem.unrelated,'keep')});
test('Failed privacy clear preserves the saved customer data',()=>{const b=harness();b.click({action:'add',id:'A79234'});const before=b.mem['hec.phase1.v1'];b.c.localStorage.setItem=()=>{throw Error('denied')};b.click({action:'confirm-clear-customer'});assert.equal(b.mem['hec.phase1.v1'],before);b.navigate('cart');assert.match(b.html(),/6,000 ر.ي/)});
test('Courier preview requires explicit entry and logout blocks history routes',()=>{const b=harness('{}','null',false);b.navigate('courier-account');assert.match(b.html(),/id="courier-login-form"/);b.click({action:'courier-enter'});b.navigate('courier-account');assert.match(b.html(),/courier-profile/);b.click({action:'courier-confirm-logout'});b.navigate('courier-profile');assert.match(b.html(),/id="courier-login-form"/);assert.doesNotMatch(b.html(),/id="courier-profile-form"/)});
test('Failed courier transition rolls back and retry is consistent',()=>{const b=harness();b.click({action:'courier-availability'});b.click({action:'courier-availability'});const before=b.mem['hec.courier.demo.v1'],write=b.c.localStorage.setItem;b.c.localStorage.setItem=()=>{throw Error('full')};b.click({action:'courier-accept',id:'DEMO-7663'});assert.equal(b.mem['hec.courier.demo.v1'],before);b.c.localStorage.setItem=write;b.click({action:'courier-accept',id:'DEMO-7663'});assert.equal(b.courier().jobs.find(j=>j.id==='DEMO-7663').status,'accepted')});
test('Cash delivery requires explicit collection confirmation',()=>{const b=harness();b.click({action:'courier-accept',id:'DEMO-7663'});b.click({action:'courier-onway',id:'DEMO-7663'});b.click({action:'courier-confirm-deliver',id:'DEMO-7663'});assert.equal(b.courier().jobs.find(j=>j.id==='DEMO-7663').status,'onway');assert.match(b.elements['#toast'].innerHTML,/تحصيل/) });
test('Courier privacy clear persists empty data and ends preview access',()=>{const b=harness();b.click({action:'add',id:'K0650'});const customer=b.mem['hec.phase1.v1'];b.click({action:'confirm-clear-courier'});assert.equal(b.courier().jobs.length,0);assert.equal(b.courier().online,false);assert.equal(b.mem['hec.phase1.v1'],customer);b.navigate('courier-home');assert.match(b.html(),/id="courier-login-form"/)});
test('Hostile and unknown route text never becomes active HTML',()=>{const b=harness();b.navigate('<img-onerror=alert(1)>');assert.doesNotMatch(b.html(),/<img-onerror/);b.navigate('admin-list/<script>');assert.doesNotMatch(b.html(),/<script>/)});
test('Restored prepaid fixtures cannot acquire a second cash collection',()=>{const b=harness('{}',JSON.stringify({jobs:[{id:'DEMO-6050',status:'delivered',collected:1750,paid:true}],profile:{}}));b.click({action:'courier-availability'});assert.equal(b.courier().jobs[0].collected,0);assert.equal(b.courier().jobs[0].paid,true)});
console.log(`${tests} functional checks passed`);
module.exports={harness};
