/* Authorization contract tests. Trusted transport fixtures exist only in this test process. */
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../app/src/main/assets/web'),flush=()=>new Promise(r=>setImmediate(r));let total=0;
async function test(name,fn){await fn();console.log('PASS '+name);total++}
function harness({enabled=true,session={authenticated:true,user:'manager@example.test',roles:['System Manager']},list=[],save=null}={}){
 const calls=[],events={},timers=[],feedback={textContent:''};let html='',dialog='',toast='',clock=1000;
 const adapter={enabled,async session(){calls.push(['session']);if(session instanceof Error)throw session;return session},async list(id){calls.push(['list',id]);if(list instanceof Error)throw list;return list},async save(...args){calls.push(['save',...args]);if(save)await save(...args);return {ok:true}},async archive(...args){calls.push(['archive',...args]);return {ok:true}}};
 const c={console,Date:class extends Date{static now(){return clock}},setTimeout:fn=>(timers.push(fn),timers.length),clearTimeout(){},HECAdminConfig:{modules:[{id:'offer-bundles',title:'الحزم',fields:[['title','العنوان','text'],['total','الإجمالي','number'],['allocation','المكونات','allocation']]}],sections:[{id:'home',title:'الرئيسية',tabs:['home']},{id:'shop',title:'تسوق',tabs:['products','categories']},{id:'offers',title:'العروض',tabs:['campaigns','golden','coupons']},{id:'orders',title:'طلباتي',tabs:['orders','returns','couriers','abandoned','reports']},{id:'account',title:'حسابي',tabs:['wallet','loyalty','affiliate','customers','messages','notifications','newsletter']},{id:'system',title:'النظام',tabs:['users','settings','audit','videos']}]},HECPicker:{syncPricing(){},collection(){return ''},allocationSearch(){return ''}},HECManagementTransport:adapter,location:{hash:'#admin/products'},HEC:{products:[],departments:[],homeCampaigns:[],homeSections:[]},HECStore:{search:s=>s.toLowerCase(),digits:s=>s},Experience:{validExternal:()=>false},document:{hidden:false,addEventListener:(e,f)=>events[e]=f,querySelector:()=>feedback},FormData:class{constructor(f){this.v=f.values}get(k){return this.v[k]??null}has(k){return k in this.v}}};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'marketing.js'),'utf8'),c);vm.runInContext(fs.readFileSync(path.join(root,'management.js'),'utf8'),c);
 const ui={esc:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),icon:()=>'<svg></svg>',title:s=>s,render(){html=c.Management.render();dialog=''},dialog(t,b){dialog=b},toast:s=>toast=s,go:r=>{c.location.hash='#'+r;ui.render()}};c.Management.init(ui);ui.render();return {c,calls,events,timers,adapter,auth:()=>c.Management.refresh(),html:()=>html,dialog:()=>dialog,toast:()=>toast,feedback,can:()=>c.Management.canManage(),entry:()=>c.Management.entry(),clock:v=>clock=v,click:action=>c.Management.click({dataset:typeof action==='string'?{action}:action}),submit:values=>c.Management.submit({getAttribute:()=> 'management-record-form',values}),route:r=>{c.location.hash='#admin/'+r;ui.render()},load:async()=>{c.Management.click({dataset:{action:'management-load'}});await flush();await flush()}};
}
(async()=>{
 await test('Review adapter is isolated from the future ERP guard',async()=>{const source=fs.readFileSync(path.join(root,'management-api.js'),'utf8');assert.match(source,/HECAdminPreview/);const guard=fs.readFileSync(path.join(root,'../../../../../integration/erpnext/management_guard.py'),'utf8');assert.doesNotMatch(guard,/reviewOnly|123456/);assert.match(guard,/System Manager/)});
 await test('Disabled adapter never contacts ERP or exposes dashboard modules',async()=>{const h=harness({enabled:false});await h.auth();assert.equal(h.can(),false);assert.equal(h.entry(),'');assert.equal(h.calls.length,0);assert.doesNotMatch(h.html(),/management-modules/)});
 await test('Only the exact server-authenticated System Manager role is accepted',async()=>{for(const session of [null,{authenticated:false,user:'m',roles:['System Manager']},{authenticated:true,user:'Guest',roles:['System Manager']},{authenticated:true,user:'m',roles:['System manager']},{authenticated:true,user:'m',roles:['Administrator']},{authenticated:true,user:'m',roles:'System Manager'},{authenticated:true,user:'m',roles:[]}]){const h=harness({session});await h.auth();assert.equal(h.can(),false);assert.equal(h.entry(),'')}});
 await test('Local storage and client role hints cannot grant access',async()=>{const h=harness({enabled:false});h.c.localStorage={getItem:()=>'{"roles":["System Manager"],"admin":true}'};h.c.roles=['System Manager'];h.c.isAdmin=true;await h.auth();h.route('users');assert.equal(h.can(),false);assert.doesNotMatch(h.html(),/management-records/)});
 await test('Trusted role exposes six organized administration sections',async()=>{const h=harness();await h.auth();h.route('');assert.equal(h.can(),true);assert.match(h.entry(),/data-go="admin"/);assert.equal((h.html().match(/module-open/g)||[]).length,6)});
 await test('Every management action is denied before authentication',async()=>{const h=harness({enabled:false});for(const action of ['management-new','management-load','management-edit','management-confirm-archive'])h.click({action,record:'A'});h.submit({title:'Forged'});await flush();assert.equal(h.calls.length,0);assert.equal(h.dialog(),'')});
 await test('Expiry removes data and entry without a navigation',async()=>{const h=harness({list:[{id:'A',title:'Secret catalog'}]});await h.auth();await h.load();assert.match(h.html(),/Secret catalog/);h.clock(61001);h.timers.at(-1)();assert.equal(h.can(),false);assert.equal(h.entry(),'');assert.doesNotMatch(h.html(),/Secret catalog/)});
 await test('Backgrounding revokes the role and closes open management forms',async()=>{const h=harness();await h.auth();h.click('management-new');assert.match(h.dialog(),/management-record-form/);h.c.document.hidden=true;h.events.visibilitychange();assert.equal(h.can(),false);assert.equal(h.dialog(),'')});
 await test('403 during loading clears confidential data and access',async()=>{const h=harness({list:[{id:'A',title:'Private'}]});await h.auth();await h.load();h.adapter.list=async()=>{throw {status:403}};await h.load();assert.equal(h.can(),false);assert.doesNotMatch(h.html(),/Private/)});
 await test('Server failure shows retry; no invented records',async()=>{const h=harness({list:Error('offline')});await h.auth();await h.load();assert.match(h.html(),/إعادة المحاولة/);assert.doesNotMatch(h.html(),/management-records/)});
 await test('Late responses after revocation cannot restore a role or records',async()=>{const h=harness();let resolve;h.adapter.session=()=>new Promise(r=>resolve=r);const waiting=h.auth();h.c.Management.revoke();resolve({authenticated:true,user:'manager',roles:['System Manager']});await waiting;assert.equal(h.can(),false)});
 await test('Server record and user markup is escaped',async()=>{const h=harness({session:{authenticated:true,user:'<img onerror=bad>',roles:['System Manager']},list:[{id:'A',title:'<script>bad</script>',image:'../../bad.jpg'}]});await h.auth();await h.load();assert.match(h.html(),/&lt;script>/);assert.doesNotMatch(h.html(),/<script>|<img onerror|src="assets\/\.\./)});
 await test('Read-only user role fields cannot be submitted or archived',async()=>{const h=harness({list:[{id:'A',title:'User'}]});await h.auth();h.route('users');await h.load();h.submit({recordId:'A',roles:'System Manager'});h.click({action:'management-confirm-archive',record:'A'});await flush();assert.equal(h.calls.filter(x=>['save','archive'].includes(x[0])).length,0)});
 await test('Duplicate submits produce a single write',async()=>{let finish;const h=harness({save:()=>new Promise(r=>finish=r)});await h.auth();const data={title:'New item',price:'10',category:'Kitchen',image:'',unit:'piece'};h.submit(data);h.submit(data);await flush();assert.equal(h.calls.filter(x=>x[0]==='save').length,1);finish();await flush()});
 await test('Readonly balances and caller-supplied versions are stripped',async()=>{const h=harness({list:[{id:'W1',version:'server-v2',title:'Wallet request',amount:100}]});await h.auth();h.route('wallet');await h.load();h.submit({recordId:'W1',recordVersion:'forged',amount:'999999',status:'مقبول',note:'Checked'});await flush();const write=h.calls.find(x=>x[0]==='save');assert.ok(write);assert.equal(write[4],'server-v2');assert.equal('amount' in write[3],false)});
 await test('Conflict does not show success or overwrite the server copy',async()=>{const h=harness({save:async()=>{throw {status:409}}});await h.auth();h.route('categories');h.submit({title:'Category',position:'1'});await flush();assert.match(h.feedback.textContent,/تغير هذا السجل/);assert.equal(h.toast(),'')});
 await test('401 during save immediately revokes access',async()=>{const h=harness({save:async()=>{throw {status:401}}});await h.auth();h.route('categories');h.submit({title:'Category',position:'1'});await flush();assert.equal(h.can(),false);assert.equal(h.toast(),'')});
 await test('Invalid dates, discounts, prices and unauthorized links do not write',async()=>{const h=harness();await h.auth();h.route('coupons');h.submit({title:'Coupon',discount:'101',minimum:'0',limit:'1'});h.submit({title:'Coupon',discount:'1',minimum:'0',limit:'1',startsAt:'bad'});h.route('products');h.submit({title:'Product',price:'-1'});h.route('settings');h.submit({title:'Store',facebook:'https://evil.test'});await flush();assert.equal(h.calls.filter(x=>x[0]==='save').length,0)});
 console.log(`${total} management authorization checks passed`);
})().catch(e=>{console.error(e);process.exit(1)});
