const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../build/variants'),out=path.resolve(__dirname,'../build/review20');
const seed=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../integration/frappe/hec_bridge/hec_bridge/seed.json')));
const publicData=Object.fromEntries(Object.entries(seed).filter(([k])=>!['users','customers','audit','wallet','orders','messages','couriers','affiliate','marketing-automation'].includes(k)));
let settings={values:{company:'شركة الاختبار',price_list:'قائمة التجزئة',warehouse:'المخزن الرئيسي',currency:'YER',integration_user:'support@example.test',delivery_days:3,features:{catalog:true,images:true}},version:'1',server_version:'2.0 mock',capabilities:Object.fromEntries(['catalog','stock','images','bundles','orders','order_submit','loyalty','affiliate','notifications','automation','delivery','returns'].map(k=>[k,{supported:['catalog','stock','images','bundles','orders','order_submit','notifications'].includes(k),reason:'متطلب تجريبي للتحقق من الواجهة'}]))};
const choices={'Company':['شركة الاختبار','شركة ثانية'],'Price List':['قائمة التجزئة','قائمة الجملة'],'Warehouse':['المخزن الرئيسي'],'Currency':['YER'],'User':['support@example.test'],'Customer Group':['عملاء أفراد'],'Territory':['اليمن'],'Cost Center':['المركز الرئيسي'],'Sales Taxes and Charges Template':['ضريبة البيع'],'Mode of Payment':['نقدي'],'Customer':['عميل الاختبار']};
(async()=>{fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{try{const f=path.resolve(root,'.'+req.url.split('?')[0]);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.jpg')?'image/jpeg':'text/html');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.HEC_CHROME_BIN,headless:true,args:['--no-sandbox']});const errors=[],checks=[];let customer,admin;const orderRequests=[];let createdOrder=false;
const ok=x=>{checks.push(x);console.log('PASS '+x)};
async function page(role,mock=false){const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(role+': '+e.message));if(mock){let logged=false;await p.exposeFunction('__backend',async(op,a)=>{if(op==='auth.login'){logged=true;return {authenticated:true,user:role==='admin'?'manager@example.test':'customer@example.test',roles:role==='admin'?['System Manager']:[],customer:role==='customer'?'CUST-test':null,name:'حساب الاختبار'}}if(op==='auth.context'){if(!logged)throw Error('401');return {authenticated:true,user:role==='admin'?'manager@example.test':'customer@example.test',roles:role==='admin'?['System Manager']:[],customer:role==='customer'?'CUST-test':null,name:'حساب الاختبار'}}if(op==='auth.logout'){logged=false;return {ok:true}}if(op==='public.config')return {modules:publicData,catalog:[],liveCatalog:false};if(op.startsWith('admin.')&&!logged)throw Error('403');if(op==='admin.config')return {modules:seed};if(op==='admin.list')return {rows:seed[a.module]||[]};if(op==='admin.options')return {items:(choices[a.doctype]||[]).filter(x=>!a.q||x.includes(a.q)).map(name=>({name})),has_more:false};if(op==='admin.settings')return settings;if(op==='admin.settings.save'){assert.equal(a.version,settings.version);assert.equal(a.values.company,'شركة ثانية');settings={...settings,values:a.values,version:'2'};return settings;}if(op==='admin.save'){const row=seed[a.module].find(r=>r.id===a.id);Object.assign(row,a.payload,{version:String(Number(row.version)+1)});publicData[a.module]=seed[a.module];return row}if(op==='customer.orders')return {orders:[]};if(op==='customer.order'){orderRequests.push(a.request_id);if(!createdOrder){createdOrder=true;throw Error('temporary reply loss')}return {name:'SO-MOCK-1',replayed:true}}if(op==='catalog.search')return {items:[],next_cursor:null};throw Error('unsupported '+op)});await p.addInitScript(()=>{window.HECRemote={request(id,op,args){window.__backend(op,JSON.parse(args)).then(value=>window.HECERP.receive(id,{value})).catch(e=>window.HECERP.receive(id,{error:{status:Number(e.message.match(/401|403/)?.[0]||500),message:e.message}}))}}})}await p.goto(origin+'/'+role+'/assets/web/index.html');return p}
try{
 customer=await page('customer');await customer.locator('.bottom-nav').waitFor();await customer.evaluate(()=>location.hash='account');await customer.waitForTimeout(150);assert.equal(await customer.locator('[data-go=admin]').count(),0);assert.equal(await customer.locator('[data-go=courier-login]').count(),1);await customer.evaluate(()=>location.hash='admin');await customer.waitForTimeout(100);assert.equal(await customer.evaluate(()=>location.hash),'#home');assert.equal(await customer.evaluate(()=>typeof HECAdminPreview),'undefined');assert.equal(await customer.evaluate(()=>typeof HECAdminConfig),'undefined');ok('Customer package has no dashboard, preview login or administrative routes');
 await customer.evaluate(()=>location.hash='detail/TR006');await customer.locator('[data-action=rating-open]').click();await customer.locator('[name=score][value="5"]').check();await customer.locator('#product-review-form [type=submit]').click();assert.match(await customer.locator('.rating-open').textContent(),/★★★★★/);ok('Customer rating still works after separation');
 await customer.evaluate(()=>location.hash='erp-account');await customer.locator('#erp-customer-login').waitFor();assert.match(await customer.locator('#app').textContent(),/لم يتأكد الاتصال/);ok('No-server state is explicit, without claiming a live connection');
 admin=await page('admin',true);await admin.locator('#erp-admin-login').waitFor();await admin.screenshot({path:out+'/admin-login.png'});await admin.locator('[name=user]').fill('manager@example.test');await admin.locator('[name=password]').fill('test-password');await admin.locator('#erp-admin-login .primary').click();await admin.locator('.management-sections').waitFor();ok('Separate administrator app opens with server-authenticated role check');
 await admin.evaluate(()=>location.hash='admin/erp-connection');await admin.locator('[name=erp_company]').waitFor();await admin.waitForFunction(()=>document.querySelector('[name=erp_company]').options.length>2);assert.equal(await admin.locator('[name=erp_company]').inputValue(),'شركة الاختبار');assert.equal(await admin.locator('[name=feature_automation]').isDisabled(),true);await admin.screenshot({path:out+'/erp-settings.png'});ok('Settings load server choices and prevent enabling unsupported workflow adapters');
 await admin.locator('[name=erp_company]').selectOption('شركة ثانية');await admin.locator('[data-option-query=warehouse]').fill('الرئيسي');await admin.locator('[data-erp-admin=options][data-key=warehouse]').click();await admin.locator('[name=erp_warehouse]').selectOption('المخزن الرئيسي');await admin.locator('#erp-settings-form .primary').click();await admin.waitForFunction(()=>document.body.textContent.includes('حُفظت إعدادات الربط'));assert.equal(settings.values.company,'شركة ثانية');ok('Company changes reset dependent lists; selected configuration saves to server');
 await admin.evaluate(()=>location.hash='admin/home');await admin.locator('[data-action=management-edit][data-record=deals]').click();await admin.locator('[name=displayTitle]').fill('أي قطعة 500 ر.ي — اختبار المزامنة');await admin.locator('#management-record-form [type=submit]').click();await admin.locator('#dialog').waitFor({state:'hidden'});await customer.close();customer=await page('customer',true);await customer.waitForFunction(()=>document.body.textContent.includes('أي قطعة 500'));assert.match(await customer.locator('.section-deals h2').textContent(),/أي قطعة 500/);ok('An admin content edit reaches a distinct customer app through the shared service contract');
 await admin.evaluate(()=>location.hash='admin/customer-links');await admin.locator('[data-action=management-new]').click();await admin.waitForFunction(()=>document.querySelector('[name=customer]')?.options.length>1);await admin.locator('[name=customer]').selectOption('عميل الاختبار');await admin.locator('[data-action=close]').click();ok('Customer mapping form offers server-backed user, customer and company dropdowns');
 await customer.evaluate(()=>location.hash='erp-account');await customer.locator('[name=user]').fill('customer@example.test');await customer.locator('[name=password]').fill('customer-test-password');await customer.locator('#erp-customer-login .primary').click();await customer.waitForFunction(()=>HECERP.context()?.customer);const code='ERP_'+('a'.repeat(24));await customer.evaluate(code=>{HECERP.mergeProducts([{app_id:code,item_code:'ERP REAL ITEM',item_name:'صنف اختبار الربط',rate:500,image:'logo.jpg',stock_uom:'حبة',item_group:'أدوات المطبخ'}]);location.hash='detail/'+code},code);await customer.locator('[data-action=add][data-id="'+code+'"]').last().click();await customer.evaluate(()=>location.hash='checkout');await customer.locator('[name=name]').fill('مستلم الاختبار');await customer.locator('[name=phone]').fill('777123456');await customer.locator('[name=address]').fill('عنوان الاختبار');await customer.locator('#checkout-form [type=submit]').click();await customer.waitForTimeout(150);await customer.locator('#checkout-form [type=submit]').click();await customer.waitForFunction(()=>location.hash==='#erp-account');assert.equal(orderRequests.length,2);assert.equal(orderRequests[0],orderRequests[1]);assert.equal(await customer.evaluate(()=>localStorage.getItem('hec.erp.order.pending.v1')),null);ok('Lost order reply retries with the same idempotency key and clears the cart only after confirmation');
 const leaks=await customer.evaluate(()=>JSON.stringify(localStorage));assert.equal(leaks.includes('customer-test-password'),false);ok('Customer password is not retained in local storage');
 for(const width of [320,390,460]){await admin.setViewportSize({width,height:844});await admin.evaluate(()=>location.hash='admin/erp-connection');await admin.locator('[name=erp_company]').waitFor();assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);await customer.setViewportSize({width,height:844});for(const hash of ['home','shop','account']){await customer.evaluate(h=>location.hash=h,hash);await customer.waitForTimeout(100);assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false)}}ok('Both applications fit 320/390/460px phones without horizontal overflow');
 await admin.setViewportSize({width:390,height:844});await admin.evaluate(()=>location.hash='admin');await admin.waitForTimeout(200);await admin.screenshot({path:out+'/admin-dashboard.png'});await customer.setViewportSize({width:390,height:844});await customer.evaluate(()=>location.hash='home');await customer.waitForTimeout(500);await customer.screenshot({path:out+'/customer-home.png'});const preview=await page('admin');await preview.locator('[data-admin-preview]').click();await preview.locator('#management-login-form').waitFor();await preview.locator('[name=username]').fill('admin');await preview.locator('[name=password]').fill('123456');await preview.locator('#management-login-form button').click();await preview.locator('.management-sections').waitFor();assert.equal(await preview.evaluate(()=>HECManagementTransport.mode),'local-preview');await preview.close();ok('Local admin review is isolated from ERP credentials and unavailable in the customer APK');assert.deepEqual(errors,[]);ok('No browser runtime errors');fs.writeFileSync(out+'/result.json',JSON.stringify({checks,errors,backend:'mock contract only; target server unreachable'},null,2));
}catch(e){for(const [name,p] of [['admin',admin],['customer',customer]])if(p&&!p.isClosed()){await p.screenshot({path:out+'/'+name+'-diagnostic.png'});fs.writeFileSync(out+'/'+name+'-diagnostic.html',await p.content())}console.error(errors);throw e}finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
